FREECAD_EXTENSION = "FCStd"

PARAM_NAME = "Name"
PARAM_VAL  = "Value"
PARAM_DESC = "Description"

SPREADSHEET_OBJ = "Spreadsheet"
SPREADSHEET_COL_NAME = PARAM_NAME
SPREADSHEET_COL_VAL  = PARAM_VAL
SPREADSHEET_COL_DESC = PARAM_DESC